#[derive(Debug, Clone, Copy)]
pub struct File<'a> {
    pub chapter: &'a str,
    pub description: &'a str,
    pub listing: &'a str,
    pub status: &'a str,
}

pub fn get_files() -> &'static [File<'static>] {
    &[
        File {
            chapter: "1. getting started; 1.2. hello, world!",
            description: "a program that prints hello, world!",
            listing: "1-1",
            status: "desired",
        },
        File {
            chapter: "1. getting started; 1.3. hello, cargo!",
            description: "contents of cargo.toml generated by cargo new",
            listing: "1-2",
            status: "toml",
        },
        File {
            chapter: "2. programming a guessing game",
            description: "code that gets a guess from the user and prints it",
            listing: "2-1",
            status: "desired",
        },
        File {
            chapter: "2. programming a guessing game",
            description: "the output from running cargo build after adding the rand crate as a dependency",
            listing: "2-2",
            status: "bash",
        },
        File {
            chapter: "2. programming a guessing game",
            description: "adding code to generate a random number",
            listing: "2-3",
            status: "desired",
        },
        File {
            chapter: "2. programming a guessing game",
            description: "handling the possible return values of comparing two numbers",
            listing: "2-4",
            status: "error",
        },
        File {
            chapter: "2. programming a guessing game",
            description: "ignoring a non-number guess and asking for another guess instead of crashing the program",
            listing: "2-5",
            status: "desired",
        },
        File {
            chapter: "2. programming a guessing game",
            description: "complete guessing game code",
            listing: "2-6",
            status: "desired",
        },
        File {
            chapter: "3. common programming concepts; 3.3. functions",
            description: "a main function declaration containing one statement",
            listing: "3-1",
            status: "desired",
        },
        File {
            chapter: "3. common programming concepts; 3.5. control flow",
            description: "assigning the result of an if expression to a variable",
            listing: "3-2",
            status: "desired",
        },
        File {
            chapter: "3. common programming concepts; 3.5. control flow",
            description: "using a while loop to run code while a condition evaluates to true",
            listing: "3-3",
            status: "desired",
        },
        File {
            chapter: "3. common programming concepts; 3.5. control flow",
            description: "looping through each element of a collection using a while loop",
            listing: "3-4",
            status: "desired",
        },
        File {
            chapter: "3. common programming concepts; 3.5. control flow",
            description: "looping through each element of a collection using a for loop",
            listing: "3-5",
            status: "desired",
        },
        File {
            chapter: "4. understanding ownership; 4.1. what is ownership?",
            description: "a variable and the scope in which it is valid",
            listing: "4-1",
            status: "desired",
        },
        File {
            chapter: "4. understanding ownership; 4.1. what is ownership?",
            description: "assigning the integer value of vaiable x to y",
            listing: "4-2",
            status: "desired",
        },
        File {
            chapter: "4. understanding ownership; 4.1. what is ownership?",
            description: "functions with ownership and the scope annotated",
            listing: "4-3",
            status: "desired",
        },
        File {
            chapter: "4. understanding ownership; 4.1. what is ownership?",
            description: "transferring ownership of return values",
            listing: "4-4",
            status: "desired",
        },
        File {
            chapter: "4. understanding ownership; 4.1. what is ownership?",
            description: "returning ownership of parameters",
            listing: "4-5",
            status: "desired",
        },
        File {
            chapter: "4. understanding ownership; 4.2. references and borrowing",
            description: "attempting to modify a borrowed value",
            listing: "4-6",
            status: "error",
        },
        File {
            chapter: "4. understanding ownership; 4.3. the slice type",
            description: "the first_word function that returns a byte index value into the string parameter",
            listing: "4-7",
            status: "desired",
        },
        File {
            chapter: "4. understanding ownership; 4.3. the slice type",
            description: "storing the result from calling the first_word function and then changing the string contents",
            listing: "4-8",
            status: "desired",
        },
        File {
            chapter: "4. understanding ownership; 4.3. the slice type",
            description: "improving the first_word function by using a string slice for the type of the s parameter",
            listing: "4-9",
            status: "desired",
        },
    ]
}
